import pygame as pg

# Colors
DARK_GREEN = (4, 138, 129)
GREEN = (6, 214, 160)
BLUE = (84, 198, 235)
PURPLE = (138, 137, 192)
PINK = (205, 162, 171)
WHITE = (255, 255, 255)
BLACK = (17, 17, 17)
DARK_BLUE = (24, 29, 49)
BEIGE = (240, 233, 210)
LIGTH_BLUE = (151, 222, 206)
LIGTH_BLUE_2 = (67, 154, 151)
HIGTHLIGTHED = (255, 191, 0)

# Fonts
FONT = "Consolas"

# Window
WINDOW_HEIGHT = 700
WINDOW_WIDTH = 1366

# Pygame events
COMPUTER_CLK = pg.USEREVENT
TOGGLE_EDITOR = pg.USEREVENT + 1
PRESS_LOAD = pg.USEREVENT + 2

# Control bar
CONTROL_BAR_HEIGHT = WINDOW_HEIGHT * 0.07
CONTROL_BAR_X = 0
CONTROL_BAR_BUTTON_HEIGHT = (int)(CONTROL_BAR_HEIGHT * 0.6)
CONTROL_BAR_BUTTON_Y = (int)(CONTROL_BAR_HEIGHT * 0.2)

# Show editor button
SHOW_EDITOR_BUTTON_X = 20
SHOW_EDITOR_BUTTON_Y = CONTROL_BAR_BUTTON_Y
SHOW_EDITOR_BUTTON_WIDTH = 60
SHOW_EDITOR_BUTTON_HEIGHT = CONTROL_BAR_BUTTON_HEIGHT

# Instructions text input
ITI_OFFSET_X = WINDOW_WIDTH * 0.01
ITI_OFFSET_Y = ITI_OFFSET_X
ITI_TEXT_AREA_HEIGHT = WINDOW_HEIGHT - (ITI_OFFSET_Y * 7)
ITI_TEXT_AREA_WIDTH = WINDOW_WIDTH - (ITI_OFFSET_X * 2)

# Memory
MEMORY_WIDTH = (WINDOW_WIDTH * 0.5) / 3
MEMORY_HEIGHT = WINDOW_HEIGHT - CONTROL_BAR_HEIGHT - WINDOW_HEIGHT * 0.09
MEMORY_X = WINDOW_WIDTH - MEMORY_WIDTH - 10
MEMORY_Y = WINDOW_HEIGHT * 0.08

# HearBoards
HEARBOARD_X = MEMORY_X
HEARBOARD_Y = MEMORY_Y - 40
HEARDBOARD_WIDTH = MEMORY_WIDTH
HEARDBOARD_HEIGTH = MEMORY_HEIGHT * 0.1


# Memory cell
MEMORY_CELL_GAP_Y = 24
MEMORY_CELL_GAP_X = 12
MEMORY_CELL_WIDTH = MEMORY_WIDTH / 2 - MEMORY_CELL_GAP_X
MEMORY_CELL_HEIGHT = MEMORY_HEIGHT / 8 - MEMORY_CELL_GAP_Y
MEMORY_CELL_X = MEMORY_CELL_GAP_X / 2
MEMORY_CELL_Y = MEMORY_CELL_GAP_Y / 2

# Processor
PROCESSOR_X = WINDOW_WIDTH * 0.01
PROCESSOR_Y = PROCESSOR_X
PROCESSOR_WIDTH = WINDOW_WIDTH * 0.4
PROCESSOR_HEIGHT = PROCESSOR_WIDTH * 1.15

# ALU
ALU_X = 30
ALU_Y = 60
ALU_WIDTH = PROCESSOR_WIDTH * 0.5
ALU_HEIGHT = PROCESSOR_HEIGHT * 0.25
ALU_INPUT_WIDTH = ALU_WIDTH * 0.5
ALU_INPUT_HEIGHT = 20
ALU_INPUT_Y = -ALU_INPUT_HEIGHT - 10
ALU_OUTPUT_Y = ALU_HEIGHT + 10

# Control Unit
CONTROL_UNIT_WIDTH = PROCESSOR_WIDTH * 0.25
CONTROL_UNIT_HEIGHT = CONTROL_UNIT_WIDTH
CONTROL_UNIT_X: float = PROCESSOR_WIDTH - CONTROL_UNIT_WIDTH - ALU_X
CONTROL_UNIT_Y = ALU_Y + ALU_INPUT_Y

# PC
PC_X = CONTROL_UNIT_X
PC_WIDTH = CONTROL_UNIT_WIDTH
PC_HEIGHT = PROCESSOR_HEIGHT * 0.05
PC_Y = CONTROL_UNIT_Y + CONTROL_UNIT_HEIGHT + 10

# MBR
MBR_X = PC_X
MBR_WIDTH = PC_WIDTH
MBR_Y = PC_Y + PC_HEIGHT + 10
MBR_HEIGHT = PC_HEIGHT

# MAR
MAR_X = MBR_X
MAR_WIDTH = MBR_WIDTH
MAR_Y = MBR_Y + MBR_HEIGHT + 10
MAR_HEIGHT = MBR_HEIGHT

# IR
IR_X = MAR_X
IR_WIDTH = MAR_WIDTH
IR_Y = MAR_Y + MAR_HEIGHT + 10
IR_HEIGHT = MAR_HEIGHT

# Stack
STACK_LENGTH = 16
STACK_WIDTH = PC_WIDTH
STACK_HEIGHT = PC_HEIGHT
STACK_X = ALU_X
STACK_Y = PROCESSOR_HEIGHT - STACK_HEIGHT * STACK_LENGTH / 2 - PROCESSOR_HEIGHT * 0.03

# BUS
BUS_WIDTH = 2

# System Bus
SYSTEM_BUS_WIDTH = 20
SYSTEM_BUS_ADDRESS_X = (
    PROCESSOR_X + PROCESSOR_WIDTH + MEMORY_X / 1.3
) / 2 - SYSTEM_BUS_WIDTH * 3 / 2
SYSTEM_BUS_DATA_X = SYSTEM_BUS_ADDRESS_X + SYSTEM_BUS_WIDTH + 30
SYSTEM_BUS_CONTROL_X = SYSTEM_BUS_DATA_X + SYSTEM_BUS_WIDTH + 30
SYSTEM_BUS_HEIGHT = PROCESSOR_HEIGHT
SYSTEM_BUS_Y = PROCESSOR_Y


# Comunication between proccesor and system bus
TRANSITION_PROCESSOR_BUS_TO = SYSTEM_BUS_ADDRESS_X
TRANSITION_PROCESSOR_TO_ADDRESS_BUS_WIDTH = SYSTEM_BUS_WIDTH
TRANSITION_PROCESSOR_TO_ADDRESS_BUS_X = PROCESSOR_WIDTH
TRANSITION_PROCESSOR_TO_ADDRESS_BUS_Y = MAR_Y + MAR_HEIGHT - MAR_HEIGHT / 8

TRANSITION_PROCESSOR_BUS_DATA_TO = SYSTEM_BUS_DATA_X
TRANSITION_PROCESSOR_TO_DATA_BUS_WIDTH = SYSTEM_BUS_WIDTH
TRANSITION_PROCESSOR_TO_DATA_BUS_X = PROCESSOR_WIDTH
TRANSITION_PROCESSOR_TO_DATA_BUS_Y = MBR_Y + MBR_HEIGHT - MBR_HEIGHT / 8


TRANSITION_PROCESSOR_BUS_CONTROL_TO = SYSTEM_BUS_CONTROL_X
TRANSITION_PROCESSOR_TO_CONTROL_BUS_WIDTH = SYSTEM_BUS_WIDTH
TRANSITION_PROCESSOR_TO_CONTROL_BUS_X = PROCESSOR_WIDTH
TRANSITION_PROCESSOR_TO_CONTROL_BUS_Y = CONTROL_UNIT_Y + CONTROL_UNIT_HEIGHT / 1.5


# Comunication between bus and memory

TRANSITION_ADDRESS_BUS_TO_MEMORY = MEMORY_X / 1.25
TRANSITION_ADDRESS_BUS_TO_MEMORY_WIDTH = SYSTEM_BUS_WIDTH
TRANSITION_ADDRESS_BUS_TO_MEMORY_X = SYSTEM_BUS_ADDRESS_X
TRANSITION_ADDRESS_BUS_TO_MEMORY_Y = TRANSITION_PROCESSOR_TO_ADDRESS_BUS_Y * 1.5

TRANSITION_DATA_BUS_TO_MEMORY = TRANSITION_ADDRESS_BUS_TO_MEMORY
TRANSITION_DATA_BUS_TO_MEMORY_WIDTH = SYSTEM_BUS_WIDTH
TRANSITION_DATA_BUS_TO_MEMORY_X = SYSTEM_BUS_DATA_X
TRANSITION_DATA_BUS_TO_MEMORY_Y = TRANSITION_ADDRESS_BUS_TO_MEMORY_Y + 40


TRANSITION_CONTROL_BUS_TO_MEMORY = TRANSITION_DATA_BUS_TO_MEMORY
TRANSITION_CONTROL_BUS_TO_MEMORY_WIDTH = SYSTEM_BUS_WIDTH
TRANSITION_CONTROL_BUS_TO_MEMORY_X = SYSTEM_BUS_CONTROL_X
TRANSITION_CONTROL_BUS_TO_MEMORY_Y = TRANSITION_DATA_BUS_TO_MEMORY_Y + 40
