from enum import Enum


class ControlSignal(Enum):
    NONE = "NONE"
    COPY_PC_TO_MAR = "COPY_PC_TO_MAR"
    COPY_MBR_TO_MAR = "COPY_MBR_TO_MAR"
    COPY_MBR_TO_IR = "COPY_MBR_TO_IR"
    COPY_OPERAND_TO_MAR = "COPY_OPERAND_TO_MAR"
    COPY_ALU_TO_MBR = "COPY_ALU_TO_MBR"
    READ_FROM_MEMORY = "READ_FROM_MEMORY"
    WRITE_TO_MEMORY = "WRITE_TO_MEMORY"
    COPY_DATA_IFACE_TO_MBR = "COPY_DATA_IFACE_TO_MBR"
    INCREASE_PC = "INCREASE_PC"
    PUSH_MBR_TO_STACK = "PUSH_MBR_TO_STACK"
    POP_STACK_TO_MBR = "POP_STACK_TO_MBR"
    PUSH_ALU_TO_STACK = "PUSH_ALU_TO_STACK"
    POP_STACK_TO_ALU = "POP_STACK_TO_ALU"
    COPY_CODOP_TO_ALU = "COPY_CODOP_TO_ALU"
    EXECUTE_ALU = "EXECUTE_ALU"
    COPY_MBR_TO_PC_IF_TRUE = "COPY_MBR_TO_PC_IF_TRUE"
    CLEAR_PIPELINE = "CLEAR_PIPELINE"

    DONE = "DONE"

    LOCK_MAR = "LOCK_MAR"
    LOCK_MBR = "LOCK_MBR"
    LOCK_ALU = "LOCK_ALU"
    LOCK_ADDRESS_BUS = "LOCK_ADDRESS_BUS"
    LOCK_DATA_BUS = "LOCK_DATA_BUS"
    LOCK_CONTROL_BUS = "LOCK_CONTROL_BUS"

    UNLOCK_MAR = "UNLOCK_MAR"
    UNLOCK_MBR = "UNLOCK_MBR"
    UNLOCK_ALU = "UNLOCK_ALU"
    UNLOCK_ADDRESS_BUS = "UNLOCK_ADDRESS_BUS"
    UNLOCK_DATA_BUS = "UNLOCK_DATA_BUS"
    UNLOCK_CONTROL_BUS = "UNLOCK_CONTROL_BUS"
